export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST'
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS'
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE'

export const SET_TABLE_ID = 'SET_TABLE_ID'
export const CLEAR_STATE = 'CLEAR_STATE'

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const SUBSTRACT_QUANTITY_FROM_CART = 'SUBSTRACT_QUANTITY_FROM_CART'
export const ADD_QUANTITY_FROM_CART = 'ADD_QUANTITY_FROM_CART'

export const TOGGLE_ALLERGENS_FILTER = 'TOGGLE_ALLERGENS_FILTER'
export const RESET_ALLERGENS_FILTER = 'RESET_ALLERGENS_FILTER'
export const TOGGLE_DIET_TYPE = 'TOGGLE_DIET_TYPE'

export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST'
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS'
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE'

export const UPDATE_ORDERS_STATUS_REQUEST = 'UPDATE_ORDERS_STATUS_REQUEST'
export const UPDATE_ORDERS_STATUS_SUCCESS = 'UPDATE_ORDERS_STATUS_SUCCESS'
export const UPDATE_ORDERS_STATUS_FAILURE = 'UPDATE_ORDERS_STATUS_FAILURE'

